package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/mferdian/Go-GraphQL/domain/product"
	"github.com/mferdian/Go-GraphQL/graphql/generated"
)

// ID is the resolver for the id field.
func (r *productResolver) ID(ctx context.Context, obj *product.Product) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Price is the resolver for the price field.
func (r *productResolver) Price(ctx context.Context, obj *product.Product) (float64, error) {
	panic(fmt.Errorf("not implemented: Price - price"))
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*product.Product, error) {
	panic(fmt.Errorf("not implemented: Products - products"))
}

// Product returns generated.ProductResolver implementation.
func (r *Resolver) Product() generated.ProductResolver { return &productResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type productResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateProduct(ctx context.Context, input product.CreateProductInput) (*product.Product, error) {
	panic(fmt.Errorf("not implemented: CreateProduct - createProduct"))
}
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }
type mutationResolver struct{ *Resolver }
*/
